%---------------
% facts
parent(alice, bob).
parent(alice, bill).
parent(bob, carol).
parent(carol, dennis).
parent(carol, david).

% rules
ancestor(X, Y) :- parent(X, Y).
ancestor(X, Y) :- ancestor(X, Z), ancestor(Z, Y).
family(X, Y) :- ancestor(X, Y).
family(X, Y) :- family(Y, X).

% queries
family(X, Y)?
family(alice, Y)?
family(alex, Y)?
ancestor(bob, Y)?

%---------------
% facts
age(alice, 30.00).
age(alice, Age)?
age(bob, 40.500).
weight(bob, 100.567000).

% queries
age(bob, Age)?
weight(bob, Weight)?

%---------------
% facts
address(bob, "10 someplace, somewhere").
address(carol, '123 "somestreet", sometown').

% queries
address(bob, Address)?
address(carol, Address)?

%---------------
% rules
details(X, Age, Address, Weight) :- age(X, Age), address(X, Address), weight(X, Weight).

% queries
details(bob, Age, Address, Weight)?
